config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  resources :parks do
    resources :reviews, shallow: true
  end 

  resources :users, only: [:new, :create, :show, :edit, :update]
  
  get "/", to: "parks#index", as: "home"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "sessions", to: "sessions#create", as: "sessions"
  delete "sessions", to: "sessions#destroy"
  get "logout", to: "sessions#destroy", as: "logout"
  get '/auth/facebook/callback', to: 'sessions#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

 
 
end

app/models/park.rb
class Park < ApplicationRecord
    has_many :reviews 
    has_many :users, through: :reviews  

    scope :most_reviews, -> { joins(:reviews).group(:count).first}
    scope :highest_rating, -> { joins(:reviews).where(reviews: {rating: 5}).first}
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :park
    belongs_to :user
    
    validates :title, {presence: true, length:{maximum:50}}
    validates :content, {presence: true, length:{maximum:300}}
    validates :rating, presence: true
    validates :rating, numericality: true
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :parks, through: :reviews
    
    validates :email, uniqueness: true

    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    def current_user 
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
        end 
    end 

    def logged_in?
        !!current_user
    end 

    def require_login
        redirect_to '/login' if !logged_in?
    end 
    helper_method :current_user
    helper_method :logged_in?
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
#before_action : authentication_required
    def index 
        # raise params.inspect
        @parks = Park.all
    end 

    def show
        @park = Park.find(params[:id])
    end 

    # def new
    #     @park = Park.new
    # end 

    # def create
    #     park = Park.create(park_params)
    #     redirect_to park
    # end 

    # private

    def park_params
        params.require(:park).permit(:name, :state, :description, :id, :amenity)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    
    def index
        if params[:user_id]
            @user = User.find(params[:user_id])
            @reviews = @user.reviews 

        elsif params[:park_id]
            @reviews = Review.where(park_id: params[:park_id]) 
        else 
            @reviews = Review.all
        end 
    end

    def show
        @review = Review.find(params[:id])
    end 

    def new 
        id = params[:park_id]
        if id && @park = Park.find(id)
            @review = @park.reviews.build
        else 
            @review = current_user.reviews.build
        end 
    end 

    def edit
        @review = Review.find(params[:id])
        if current_user.id == @review.user_id
            edit_review_path(@review)
        else 
            redirect_to review_path(@review), notice: 'Only review owners can edit reviews'
        end 
    end 

    def create
        @review = Review.new(review_params)
          if @review.save
            redirect_to @review, notice: 'Review was successfully created.' 
          else
            render :new 
          end
    end 

    def update
        @review = Review.find_by_id(params[:id])
        if @review.update(review_params)
            redirect_to review_path(@review), notice: 'Review was successfully updated.'
          else
            render :edit
          end
    end

    def destroy
        @review = Review.find(params[:id])
            if @review.user === current_user
               @review.destroy
               redirect_to reviews_path, notice: 'Review was successfully destroyed'
            else
                redirect_to review_path(@review), notice: 'Only review owners can delete reviews'
            end 
    end 

    private 

    def review_params
        params.require(:review).permit(:title, :rating, :content, :user_id, :park_id )
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        redirect_to current_user if logged_in?
    end 

    def create 
        if auth_hash = request.env["omniauth.auth"]
            oauth_email = request.env["omniauth.auth"]["info"]["email"]
            oauth_name = request.env["omniauth.auth"]["info"]["name"]
           if user = User.find_by(:email  => oauth_email)
                session[:user_id] = user.id
                redirect_to user_path(user.id)
           else 
                user = User.new(:email => oauth_email, :full_name => oauth_name, :password_digest => SecureRandom.hex )
                
                if user.save
                    session[:user_id] = user.id
                    redirect_to user_path(user.id)
                end 
            end  
        end 

        if params[:email]
            @user = User.find_by(email: params[:email])
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to @user
            else 
                redirect_to login_path
            end 
        end 
    end 

    def destroy
        session.delete(:user_id)
        redirect_to login_path, notice: "You are signed out"
    end 

    private
 
    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        redirect_to current_user if logged_in?
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end 
    end 
    
    def show
        require_login
        set_user
    end 

    def edit
        set_user
         if current_user != set_user
            redirect_to current_user
         end 
    end 

    def update
        @user = User.find_by_id(params[:id])
        @user.update(user_params)
        redirect_to current_user, notice: 'Profile was successfully updated.'
    end 
    
    private

    def set_user
        @user = User.find(params[:id])
    end 

    def user_params
        params.require(:user).permit(:full_name, :user_name,:email, :password, :password_confirmation )
    end 

end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/park_amenities_helper.rb
module ParkAmenitiesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<style>
body {
  background-color: lightblue;
  opacity: 1;
}

h1 {
  color: white;
  text-align: center;
}


h2 {
  color: white;
  text-align: center;
}
h3 {
  color: white;
  text-align: center;
}
p {
  font-family: verdana;
  font-size: 20px;
}

.field_with_errors {
    padding:2px;
    background-color: red;
    display: table;
 }

 .error {
     color: red;
 }
</style>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    
    
    <title>GreatOutdoorsApp</title>
    
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="/stylesheets/main.css" />  </head>

  <body>

  <div class="wrapper">
    
  <% if logged_in? %>
    You are logged in as: <%= current_user.full_name %><br>
  <% else %> 
    You are browsing as a vistor. To add a review please log-in or sing up. 
  <% end %>
  
    
  <%= yield %>
      
  <br>
  <footer class="branding">

    <% if logged_in? %>
      <%= link_to 'logout', logout_path %>|
      <%= link_to 'reviews', reviews_path %>
    <% else %> 
      <%= link_to 'Signup', signup_path %> |
      <%= link_to 'login', login_path %>
    <% end %>
    <br>
    <small>&copy; 2020 <strong>Great Outdoors </strong></small>
  </footer>
  </div>

  </body>

  </html>

app/views/parks/index.html.erb
<h1>The Great Outdoors</h1>

<p><img src="../greatoutdoors-image.png" alt="Get out and live" style="width:855px;height:595px;"></p>
<p>
Welcome to the Great Outdoors, a community of outdoor enthusiasts. This site helps users find parks and recreation areas for thier next excusion.

To view contributions you have to signup, this will enable you to view member reviews and make your own review contributions to our community members. 
</p>


<p>Select a state below to view parks and recreation areas: </p>
<ul>
<% @parks.each do |park| %>
    <li>
    <% if logged_in? %>
    <%= link_to park.name, park_path(park) %> -<%= link_to 'See views', park_reviews_path(park)%>
    <%= link_to 'Write a review', new_park_review_path(park)%>
    <% else%>
    <%= link_to park.name, park_path(park) %> -<%= link_to 'See views', park_reviews_path(park)%>
    <% end %>
    </li>
<% end %>
</ul>
Here is our highest rated park by our enthusiasts:
<%= link_to @parks.highest_rating.name, park_path(@parks.highest_rating) %>
<br>
Here is our most rated park by our enthusiasts:
<%= link_to @parks.most_reviews.name, park_path(@parks.most_reviews) %>
<br>
<% if logged_in? %>
    <%= link_to 'Click here to view your reviews', user_path(current_user.id) %>
<% end %>

    

app/views/parks/show.html.erb
<h2><%= @park.name %> </h2> 
<%= @park.state %>
<p><%= @park.description %></p>
<br>

<% if logged_in? %>
<p>Here are some helpfull reviews about this park by outdoor enthusiats just like you:</p>
<ul>
<% @park.reviews.each do |review| %>
    <li>
    Contributor:<%= link_to review.user.full_name, review_path(review) %>
    <br>
    Title: <%= review.title %> - Rating: <%= review.rating %>
    <br>
    Comments:
    <br> 
    <%= review.content %>
    </li>
<% end %>
</ul>
<br>

<%= link_to 'write a review about this park', new_review_path %>
<br>
<%= link_to 'return to home page', parks_path %>
<br>

<% else %> 
    You are browsing as a vistor. To views or add  your own review please log-in or sing up. 
<% end %>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
    
    <br>
    <%= f.label :title%>
    <%= f.text_area :title%><br>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content %><br>
    <br>
    <%= f.label :rating %>
    <%= f.number_field :rating,  max:5, min:0  %><br>
    <br>
    <%= f.collection_select :park_id, Park.all, :id, :name %>
    <br>
    <%= f.hidden_field :user_id, :value => current_user.id %>
   
    <%= f.submit %>

  <% end %>
  

app/views/reviews/edit.html.erb
<h1>Update your review</h1>
    
<%= render 'form', review: @review %>

<br>
<%= link_to 'Home page', parks_path %>| <%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<table>
  <thead>
    <tr>
        <th>Park |</th>  
        <th>Rating|</th>
        <th>Title | </th>
        <th>Review Comments</th>
        <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.park.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.title %></td>
        <td><%= review.content %></td>
          <td><%= link_to 'Show', review_path(review) %></td>
          <td><%= link_to 'Edit', edit_review_path(review) %></td>
          <td><%= button_to 'Delete', review_path(review), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Write a new review', new_review_path %>
<br>
<%= link_to 'Home page', parks_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>


<% if @review.errors.any?%>

        <ul>
        <% @review.errors.full_messages.each do |msg|%>
            <li class="error"><%= msg %></li>
            <% end%>
        </ul>
        
        <%= render 'form', review: @review %>
        
<% else %>

    <%= render 'form', review: @review %>

<% end %>

<%= link_to 'Back', reviews_path %>
<br>
<%= link_to 'Home page', parks_path %>

app/views/reviews/show.html.erb
<h2>Park Review Comments</h2>

<h3><%= link_to @review.park.name, park_path(@review.park) %></h3>

<h4>Rating: <%= @review.rating %> </h4>

<p>
<h4>Title: <%= @review.title %></h4>
<h4>Comments:</h4>
<%= @review.content %>
<h5> Contributor: <%= link_to @review.user.full_name, user_path(@review.user) %></h5>
<br>
</p>
<%= link_to 'Edit', edit_review_path(@review) %> <%= button_to 'Delete', review_path(@review), method: :delete %>
<br>
<%= link_to 'All reviews', reviews_path %><br>
<br>
<%= link_to 'Home page', parks_path %>
<br>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <br>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %> <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email %> <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %> <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %> <br>

    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<%= f.label :user_name %>
<%= f.text_field :user_name, :placeholder => "User name" %> <br>
<br>
<%= f.label :email %>
<%= f.email_field :email, :placeholder => "email" %> <br>
<br>
<%= f.label :password %>
<%= f.password_field :password %> <br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %> <br>
    
<%= f.submit %>
<% end %>
<br>
<%= link_to 'Back to your profile page', user_path(current_user.id) %>

app/views/users/new.html.erb
<% if @user.errors.any?%>

        <ul>
        <% @user.errors.full_messages.each do |msg|%>
            <li class="error"><%= msg %></li>
            <% end%>
        </ul>
        
        <%= render 'form', user: @user %>
        
<% else %>

    
<%= render 'form', user: @user %>
    
<% end %>

app/views/users/show.html.erb
<h2>Welcome <%= @user.full_name %>!</h2>

<h4>Here is your profile:</h4> 

Name: <%= @user.full_name %><br>
Username: <%= @user.user_name%><br>
email: <%= @user.email %><br>

<%= link_to 'Click here to Edit your profile', edit_user_path(current_user.id) %>
<br >
<h4>Here is a list of your reviews:</h4>

<table>
<tbody>
    <% @user.reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.title %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Delete', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

<br>
<%= link_to 'return to home page', parks_path %>
<br>